export const data = [
  {
    name: 'Light pinl Shirt',
    title: 'Nike T-shirt',
    category: 'Clothing',
    image: '/asset/img01.jpg',
    countInStock: '4',
    price: '$35',
    brand: 'Nike',
    rating: '4.5',
    numReviews: 10,
    description: 'original T-shirt',
  },
  {
    name: 'Nike Black sneakers',
    title: 'Nike Sneakers',
    category: 'Foot wears',
    image: '/asset/img02.jpg',
    countInStock: '12',
    price: '$90',
    brand: 'Nike',
    rating: '4.1',
    numReviews: 20,
    description: 'original Sneakers',
  },
  {
    name: 'Nike White sneakers',
    title: 'Nike Sneakers',
    category: 'FootWear',
    image: '/asset/img05.jpg',
    countInStock: '25',
    price: '$100',
    brand: 'Nike',
    rating: '4.9',
    numReviews: 10,
    description: 'original Sneakers',
  },
  {
    name: 'Nike Fancy sneakers',
    title: 'Nike Sneakers',
    category: 'FootWear',
    image: '/asset/img07.jpg',
    countInStock: '2',
    price: '$150',
    brand: 'Nike',
    rating: '4.7',
    numReviews: 27,
    description: 'original Sneakers',
  },
];
